package com.nyw.wanandroid.module.home.mvp;

import com.bakerj.base.loadmore.mvp.LoadMoreContract;
import com.nyw.domain.domain.bean.request.home.HomeReq;
import com.nyw.domain.domain.bean.request.home.SearchReq;
import com.nyw.domain.domain.bean.response.home.ArticlesBean;
import com.nyw.domain.domain.bean.response.home.BannerBean;
import com.nyw.libproject.loadmore.mvp.PageLoadMorePresenter;

import java.util.List;

/**
 * @author nyw
 * @date 2019/07/10
 *
 * Generated by MVPGenerator
 */
public interface SearchResultContract {
    //泛型为返回的数据类型，即Adapter中展示的数据类型
    interface View extends LoadMoreContract.View<ArticlesBean> {

    }

    //具体泛型注释可查阅 {父基类LoadMorePresenter}
    abstract class Presenter extends PageLoadMorePresenter<View, SearchReq, ArticlesBean,
            ArticlesBean> {
        public Presenter(View view) {
            super(view);
        }

        public abstract void setBody(String key);
    }
}
