package com.nyw.wanandroid.module.knowledge.mvp;

import android.util.Log;

import com.bakerj.rxretrohttp.RxRetroHttp;
import com.nyw.domain.domain.bean.response.home.KnowledgeNavBean;
import com.nyw.libproject.common.api.CBApiObserver;
import com.nyw.wanandroid.module.knowledge.data.repository.IknowledgeRepository;
import com.nyw.wanandroid.module.knowledge.data.repository.knowledgeRepositoryImpl;

import java.util.List;

/**
 * @author nyw
 * @date 2019/07/10
 *
 * Generated by MVPGenerator
 */
public class KnowledgeNaviPresenter extends KnowledgeNaviContract.Presenter{
    private IknowledgeRepository mRepository = new knowledgeRepositoryImpl();


    public KnowledgeNaviPresenter(KnowledgeNaviContract.View view) {
        super(view);
    }

    @Override
    public void getNaviBean() {
        RxRetroHttp.composeRequest(mRepository.getNaviBean(), mView)
                .subscribe(new CBApiObserver<List<KnowledgeNavBean>>() {
                    @Override
                    protected void success(List<KnowledgeNavBean> data) {
                        ((KnowledgeNaviContract.View) mView).NaviBeanGet(data);
                        Log.e("nieyuwne",data.get(0).getName());
                    }
                });
    }


}
