package com.nyw.wanandroid.module.main.mvp;

import android.content.Context;

import com.nyw.domain.domain.bean.request.home.HomeReq;
import com.nyw.domain.domain.bean.response.home.ArticleBean;
import com.nyw.wanandroid.module.main.data.repository.ImainRepository;
import com.nyw.wanandroid.module.main.data.repository.mainRepositoryImpl;

import java.util.List;

import io.reactivex.Observable;

/**
 * @author nyw
 * @date 2019/06/27
 *
 * Generated by MVPGenerator
 */
public class homePresenter extends homeContract.Presenter {
    private ImainRepository mRepository = new mainRepositoryImpl();
    private int  page;

    public homePresenter(homeContract.View view,int page) {
        super(view);
        this.page=page;
    }


    @Override
    protected HomeReq getQuestBody() {
        HomeReq req = new HomeReq();
        req.setPage(page);
        return req;
    }

    @Override
    protected ArticleBean castDataToDest(ArticleBean articleBean) {
        return articleBean;
    }

    @Override
    protected Observable<List<ArticleBean>> getRefreshLoadObservable(HomeReq body) {
        return mRepository.getArticleBean(body);
    }

}
