package com.nyw.wanandroid.module.main.mvp;

import com.bakerj.base.BasePresenter;
import com.bakerj.base.BaseView;
import com.bakerj.base.loadmore.mvp.LoadMoreContract;
import com.nyw.domain.domain.bean.request.home.HomeReq;
import com.nyw.domain.domain.bean.response.home.ArticleBean;
import com.nyw.libproject.loadmore.mvp.PageLoadMorePresenter;

/**
 * @author nyw
 * @date 2019/06/27
 *
 * Generated by MVPGenerator
 */
public interface homeContract {
    //泛型为返回的数据类型，即Adapter中展示的数据类型
    interface View extends LoadMoreContract.View<ArticleBean> {
    }

    //具体泛型注释可查阅 {父基类LoadMorePresenter}
    abstract class Presenter extends PageLoadMorePresenter<View, HomeReq,ArticleBean,
                ArticleBean> {
        public Presenter(View view) {
            super(view);

        }
    }
}
