package com.nyw.wanandroid.module.main.mvp;

import com.nyw.wanandroid.module.main.data.repository.ImainRepository;
import com.nyw.wanandroid.module.main.data.repository.mainRepositoryImpl;

/**
 * @author nyw
 * @date 2019/06/27
 *
 * Generated by MVPGenerator
 */
public class mainPresenter extends mainContract.Presenter {
    private ImainRepository mRepository = new mainRepositoryImpl();

    public mainPresenter(mainContract.View view) {
        super(view);
    }
}
