package com.nyw.wanandroid.module.main.mvp;

import com.bakerj.base.BasePresenter;
import com.bakerj.base.BaseView;

/**
 * @author nyw
 * @date 2019/06/27
 *
 * Generated by MVPGenerator
 */
public interface mainContract {
    interface View extends BaseView {
    }

    abstract class Presenter extends BasePresenter<View> {
        public Presenter(View view) {
            super(view);
        }
    }
}
