package com.nyw.wanandroid.module.wechat.mvp;

import com.bakerj.rxretrohttp.RxRetroHttp;
import com.blankj.utilcode.util.ToastUtils;
import com.nyw.domain.common.loadmore.PageLoadMoreResponse;
import com.nyw.domain.domain.bean.request.home.HomeReq;
import com.nyw.domain.domain.bean.request.wechat.WechatReq;
import com.nyw.domain.domain.bean.response.home.ArticlesBean;
import com.nyw.domain.domain.bean.response.home.KnowledgeArtBean;
import com.nyw.libproject.common.api.CBApiObserver;
import com.nyw.wanandroid.module.wechat.data.repository.IwechatRepository;
import com.nyw.wanandroid.module.wechat.data.repository.wechatRepositoryImpl;

import java.util.List;

import io.reactivex.Observable;

/**
 * @author nyw
 * @date 2019/07/10
 *
 * Generated by MVPGenerator
 */
public class wechatListPresenter extends wechatListContract.Presenter{
    private IwechatRepository mRepository = new wechatRepositoryImpl();
    private int id;

    public wechatListPresenter(wechatListContract.View view,int id) {
        super(view);
        this.id=id;
        ToastUtils.showLong(id+"");
    }
    @Override
    protected WechatReq getQuestBody() {
        WechatReq req = new WechatReq();
        req.setId(id);
        return req;
    }

    @Override
    protected void setUpRefreshBody(WechatReq body) {
        super.setUpRefreshBody(body);
        body.setId(id);
    }

    @Override
    protected boolean hasMore(List<ArticlesBean> data) {
        return true;
    }

    @Override
    protected ArticlesBean castDataToDest(ArticlesBean articlesBean) {
        return articlesBean;
    }

    @Override
    protected Observable<List<ArticlesBean>> getRefreshLoadObservable(WechatReq body) {
        return mRepository.getArticleBean(body).map(PageLoadMoreResponse::getDatas);
    }
}
