package com.nyw.wanandroid.module.main.data.repository;

import com.nyw.domain.common.loadmore.PageLoadMoreResponse;
import com.nyw.domain.domain.bean.request.home.HomeReq;
import com.nyw.domain.domain.bean.response.home.ArticleBean;
import com.nyw.domain.domain.bean.response.home.BannerBean;
import com.nyw.wanandroid.module.main.data.repository.datastore.mainLocalDataStore;
import com.nyw.wanandroid.module.main.data.repository.datastore.mainRemoteDataStore;

import java.util.List;

import io.reactivex.Observable;

/**
 * @author nyw
 * @date 2019/06/27
 *
 * Generated by MVPGenerator
 */
public class mainRepositoryImpl implements ImainRepository{
    private mainLocalDataStore mLocalDataStore = new mainLocalDataStore();
    private mainRemoteDataStore mRemoteDataStore = new mainRemoteDataStore();


    @Override
    public Observable<PageLoadMoreResponse<ArticleBean>> getArticleBean(HomeReq body) {
        return mRemoteDataStore.getArticleList(body);
    }

    @Override
    public Observable<List<BannerBean>> getBanner() {
        return mRemoteDataStore.getBannerList();
    }
}
