package com.nyw.wanandroid.module.main.data.repository;

import com.nyw.wanandroid.module.main.data.repository.datastore.mainLocalDataStore;
import com.nyw.wanandroid.module.main.data.repository.datastore.mainRemoteDataStore;

/**
 * @author nyw
 * @date 2019/06/27
 *
 * Generated by MVPGenerator
 */
public class mainRepositoryImpl implements ImainRepository {
    private mainLocalDataStore mLocalDataStore = new mainLocalDataStore();
    private mainRemoteDataStore mRemoteDataStore = new mainRemoteDataStore();
}
