package com.nyw.wanandroid.module.project.mvp;


import com.nyw.domain.common.loadmore.PageLoadMoreResponse;
import com.nyw.domain.domain.bean.request.project.ProjectReq;
import com.nyw.domain.domain.bean.response.home.ArticlesBean;
import com.nyw.wanandroid.module.project.data.repository.IprojectRepository;
import com.nyw.wanandroid.module.project.data.repository.projectRepositoryImpl;

import java.util.List;

import io.reactivex.Observable;

/**
 * @author nyw
 * @date 2019/07/10
 *
 * Generated by MVPGenerator
 */
public class projectListPresenter extends projectListContract.Presenter{
    private IprojectRepository mRepository = new projectRepositoryImpl();
    private int cid;


    public projectListPresenter(projectListContract.View view,int cid) {
        super(view);
        this.cid=cid;
    }

    @Override
    protected ProjectReq getQuestBody() {
        ProjectReq req=new ProjectReq();
        req.setCid(cid);
        return req;
    }

    @Override
    protected void setUpRefreshBody(ProjectReq body) {
        super.setUpRefreshBody(body);
        body.setCid(cid);
    }

    @Override
    protected boolean hasMore(List<ArticlesBean> data) {
        return true;
    }

    @Override
    protected Observable<List<ArticlesBean>> getRefreshLoadObservable(ProjectReq body) {
        return mRepository.getArticleBean(body).map(PageLoadMoreResponse::getDatas);
    }

    @Override
    protected ArticlesBean castDataToDest(ArticlesBean articlesBean) {
        return articlesBean;
    }


}
