package com.nyw.wanandroid.module.project.mvp;


import com.bakerj.rxretrohttp.RxRetroHttp;
import com.nyw.domain.common.api.WanApiResult;
import com.nyw.domain.common.loadmore.PageLoadMoreResponse;
import com.nyw.domain.domain.bean.request.project.ProjectReq;
import com.nyw.domain.domain.bean.response.home.ArticleBean;
import com.nyw.libproject.common.api.CBApiObserver;
import com.nyw.wanandroid.module.home.data.repository.IhomeRepository;
import com.nyw.wanandroid.module.home.data.repository.homeRepositoryImpl;
import com.nyw.wanandroid.module.home.mvp.SearchResultContract;
import com.nyw.wanandroid.module.project.data.repository.IprojectRepository;
import com.nyw.wanandroid.module.project.data.repository.projectRepositoryImpl;

import java.util.List;

import io.reactivex.Observable;

/**
 * @author nyw
 * @date 2019/07/10
 *
 * Generated by MVPGenerator
 */
public class projectListPresenter extends projectListContract.Presenter{
    private IprojectRepository mRepository = new projectRepositoryImpl();
    private IhomeRepository Repository = new homeRepositoryImpl();

    private int cid;


    public projectListPresenter(projectListContract.View view,int cid) {
        super(view);
        this.cid=cid;
    }

    @Override
    protected ProjectReq getQuestBody() {
        ProjectReq req=new ProjectReq();
        req.setCid(cid);
        return req;
    }

    @Override
    protected void setUpRefreshBody(ProjectReq body) {
        super.setUpRefreshBody(body);
        body.setCid(cid);
    }

    @Override
    protected boolean hasMore(List<ArticleBean> data) {
        return true;
    }

    @Override
    protected Observable<List<ArticleBean>> getRefreshLoadObservable(ProjectReq body) {
        return mRepository.getArticleBean(body).map(PageLoadMoreResponse::getDatas);
    }

    @Override
    protected ArticleBean castDataToDest(ArticleBean articleBean) {
        return articleBean;
    }


    @Override
    public void Collect(int id) {
        RxRetroHttp.composeRequest(Repository.Collect(id), mView)
                .subscribe(new CBApiObserver<WanApiResult>() {
                    @Override
                    protected void success(WanApiResult data) {
                        ((projectListContract.View) mView).CollectSuccess();
                    }
                });
    }

    @Override
    public void UnCollect(int id) {
        RxRetroHttp.composeRequest(Repository.Uncollect(id), mView)
                .subscribe(new CBApiObserver<WanApiResult>() {
                    @Override
                    protected void success(WanApiResult data) {
                        ((projectListContract.View) mView).UnCollectSuccess();
                    }
                });
    }
}
