package com.nyw.wanandroid.module.main.data.repository.datastore;

import com.bakerj.rxretrohttp.RxRetroHttp;
import com.nyw.wanandroid.module.main.data.api.mainApiService;

/**
 * @author nyw
 * @date 2019/06/27
 *
 * Generated by MVPGenerator
 */
public class mainRemoteDataStore {
    private mainApiService mService = RxRetroHttp.create(mainApiService.class);


}
