package com.nyw.wanandroid.module.main.data.api;

import com.nyw.domain.common.api.WanApiResult;
import com.nyw.domain.common.loadmore.PageLoadMoreResponse;
import com.nyw.domain.domain.bean.response.home.ArticleBean;
import com.nyw.domain.domain.bean.response.home.BannerBean;
import com.nyw.domain.domain.common.API;

import java.util.List;

import io.reactivex.Observable;
import retrofit2.http.GET;
import retrofit2.http.Path;
import retrofit2.http.Query;

/**
 * @author nyw
 * @date 2019/06/27
 *
 * Generated by MVPGenerator
 */
public interface mainApiService {

    /**
     * 首页文章列表
     * 方法：GET
     * 参数：页码，拼接在连接中，从0开始。
     */
    @GET(API.HomeAPI.article)
    Observable<PageLoadMoreResponse<ArticleBean>> getArticleList(
            @Path("page") int page);

    /**
     * 首页banner
     */
    @GET(API.HomeAPI.banner)
    Observable<WanApiResult<List<BannerBean>>> getBanner();
}
